/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import entidades.Colectivo;
import java.awt.Color;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

/**
 *
 * @author Marcela
 */
public class PanelColectivo extends javax.swing.JPanel {

    /**
     * Creates new form PanelColectivo
     */
    public PanelColectivo() {
        initComponents();
    }
    
    public PanelColectivo(Colectivo colectivo) {
        initComponents();
        System.out.println(colectivo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void mouseEnter(JPanel panel) {
        Color currentColor = panel.getBackground();
        float[] hsb = Color.RGBtoHSB(currentColor.getRed(), currentColor.getGreen(), currentColor.getBlue(), null);
        float brightness = hsb[2];
        float newBrightness = Math.min(brightness + 0.1f, 1.0f);
        Color newColor = Color.getHSBColor(hsb[0], hsb[1], newBrightness);
        panel.setBackground(newColor);
    }

    private void mouseExit(JPanel panel) {
        Color currentColor = panel.getBackground();
        float[] hsb = Color.RGBtoHSB(currentColor.getRed(), currentColor.getGreen(), currentColor.getBlue(), null);
        float brightness = hsb[2];
        float newBrightness = Math.max(brightness - 0.1f, 0.0f);
        Color newColor = Color.getHSBColor(hsb[0], hsb[1], newBrightness);
        panel.setBackground(newColor);
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SpinnerCantPasajeros = new javax.swing.JSpinner();
        TxtModelo = new javax.swing.JTextField();
        TxtPatente = new javax.swing.JTextField();
        PanelBtnEditarColectivo = new javax.swing.JPanel();
        BtnEditarColectivo = new javax.swing.JLabel("Editar", SwingConstants.CENTER);

        Fondo.setBackground(new java.awt.Color(248, 248, 255));
        Fondo.setPreferredSize(new java.awt.Dimension(446, 249));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Capacidad de pasajeros:");
        Fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Modelo:");
        Fondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 30));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Patente:");
        Fondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 30));
        Fondo.add(SpinnerCantPasajeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 270, 30));
        Fondo.add(TxtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 270, 30));
        Fondo.add(TxtPatente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 270, 30));

        PanelBtnEditarColectivo.setBackground(new java.awt.Color(64, 121, 140));

        BtnEditarColectivo.setForeground(new java.awt.Color(255, 255, 255));
        BtnEditarColectivo.setText("Editar");
        BtnEditarColectivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnEditarColectivoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnEditarColectivoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnEditarColectivoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PanelBtnEditarColectivoLayout = new javax.swing.GroupLayout(PanelBtnEditarColectivo);
        PanelBtnEditarColectivo.setLayout(PanelBtnEditarColectivoLayout);
        PanelBtnEditarColectivoLayout.setHorizontalGroup(
            PanelBtnEditarColectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBtnEditarColectivoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnEditarColectivo, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelBtnEditarColectivoLayout.setVerticalGroup(
            PanelBtnEditarColectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBtnEditarColectivoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnEditarColectivo, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        Fondo.add(PanelBtnEditarColectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnEditarColectivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEditarColectivoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnEditarColectivoMouseClicked

    private void BtnEditarColectivoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEditarColectivoMouseEntered
        // TODO add your handling code here:
        mouseEnter(PanelBtnEditarColectivo);
    }//GEN-LAST:event_BtnEditarColectivoMouseEntered

    private void BtnEditarColectivoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEditarColectivoMouseExited
        // TODO add your handling code here:
        mouseExit(PanelBtnEditarColectivo);
    }//GEN-LAST:event_BtnEditarColectivoMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtnEditarColectivo;
    private javax.swing.JPanel Fondo;
    private javax.swing.JPanel PanelBtnEditarColectivo;
    private javax.swing.JSpinner SpinnerCantPasajeros;
    private javax.swing.JTextField TxtModelo;
    private javax.swing.JTextField TxtPatente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
